[project]
name = "markdown-to-pdf"
version = "0.1.0"
description = "A Python tool to convert Markdown files to PDF with advanced styling and features."
authors = [
    { name = "Neo Alienson", email = "neo@01man.com" }
]
dependencies = [
    "markdown", # For basic Markdown parsing
    "WeasyPrint", # For HTML to PDF conversion and CSS styling
    "Pygments", # For code highlighting
    "beautifulsoup4", # For HTML manipulation
    "requests", # For fetching external resources like images
    "Pillow", # For image processing
]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
markdown-to-pdf = "markdown_to_pdf.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
